name: Render Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger-render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render Backend Deploy
        run: |
          if [ -n "${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_URL }}" ]; then
            curl -X POST "${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_URL }}"
          else
            echo "No backend deploy hook set, skipping."
          fi

      - name: Trigger Render Frontend Deploy
        run: |
          if [ -n "${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_URL }}" ]; then
            curl -X POST "${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_URL }}"
          else
            echo "No frontend deploy hook set, skipping."
          fi
