name: Render Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger-backend-deploy:
    if: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_URL != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render Backend Deploy
        run: curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_URL }}
  
  trigger-frontend-deploy:
    if: ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_URL != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Trigger Render Frontend Deploy
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_URL }}
